### ISSUE TITLE
Database error is showng

### ISSUE THREAD

**Issue by vallavanj** [mageplaza/magento-2-product-slider#11]
I install is working fine But database table is not exits error is showing.
Error:

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'position' in 'where clause', query was: SELECT `main_table`.* FROM `magestore_bannerslider_slider` AS `main_table` WHERE (`position` = 'page-bottom') AND (`status` = '1')
Exception #1 (PDOException): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'position' in 'where clause'

Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'position' in 'where clause', query was: SELECT `main_table`.* FROM `magestore_bannerslider_slider` AS `main_table` WHERE (`position` = 'page-bottom') AND (`status` = '1')
#0 C:\xampp\htdocs\magento_sample\vendor\magento\framework\DB\Statement\Pdo\Mysql.php(95): Zend_Db_Statement_Pdo->_execute(Array)
#1 C:\xampp\htdocs\magento_sample\vendor\magento\zendframework1\library\Zend\Db\Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 C:\xampp\htdocs\magento_sample\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 C:\xampp\htdocs\magento_sample\vendor\magento\zendframework1\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT `main_ta...', Array)
#4 C:\xampp\htdocs\magento_sample\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(465): Zend_Db_Adapter_Pdo_Abstract->query('SELECT `main_ta...', Array)
#5 C:\xampp\htdocs\magento_sample\vendor\magento\framework\DB\Adapter\Pdo\Mysql.php(520): Magento\Framework\DB\Adapter\Pdo\Mysql->_query(Object(Magento\Framework\DB\Select), Array)
#6 C:\xampp\htdocs\magento_sample\vendor\magento\zendframework1\library\Zend\Db\Adapter\Abstract.php(737): Magento\Framework\DB\Adapter\Pdo\Mysql->query(Object(Magento\Framework\DB\Select), Array)
#7 C:\xampp\htdocs\magento_sample\vendor\magento\framework\Data\Collection\Db\FetchStrategy\Query.php(21): Zend_Db_Adapter_Abstract->fetchAll(Object(Magento\Framework\DB\Select), Array)
#8 C:\xampp\htdocs\magento_sample\vendor\magento\framework\Data\Collection\AbstractDb.php(772): Magento\Framework\Data\Collection\Db\FetchStrategy\Query->fetchAll(Object(Magento\Framework\DB\Select), Array)
#9 C:\xampp\htdocs\magento_sample\vendor\magento\framework\Data\Collection\AbstractDb.php(668): Magento\Framework\Data\Collection\AbstractDb->_fetchAll(Object(Magento\Framework\DB\Select))
#10 C:\xampp\htdocs\magento_sample\vendor\magento\framework\Data\Collection\AbstractDb.php(572): Magento\Framework\Data\Collection\AbstractDb->getData()
#11 C:\xampp\htdocs\magento_sample\vendor\magento\framework\Data\Collection\AbstractDb.php(557): Magento\Framework\Data\Collection\AbstractDb->loadWithFilter(false, false)
#12 C:\xampp\htdocs\magento_sample\vendor\magento\framework\Data\Collection.php(820): Magento\Framework\Data\Collection\AbstractDb->load()
#13 C:\xampp\htdocs\magento_sample\app\code\Magestore\Bannerslider\Block\Bannerslider.php(107): Magento\Framework\Data\Collection->getIterator()
#14 C:\xampp\htdocs\magento_sample\app\code\Magestore\Bannerslider\Block\Bannerslider.php(129): Magestore\Bannerslider\Block\Bannerslider->appendChildBlockSliders(Object(Magestore\Bannerslider\Model\ResourceModel\Slider\Collection))
#15 [internal function]: Magestore\Bannerslider\Block\Bannerslider->setPosition('page-bottom')
#16C:\xampp\htdocs\magento_sample\vendor\magento\framework\View\Layout\Generator\Block.php(284): call_user_func_array(Array, Array)
#17C:\xampp\htdocs\magento_sample\vendor\magento\framework\View\Layout\Generator\Block.php(159): Magento\Framework\View\Layout\Generator\Block->generateAction(Object(Magestore\Bannerslider\Block\Bannerslider), 'setPosition', Array)

Please suggest me something are you send your sql table

**Comment by haitv282** [comment]
Hi Vallavanj,

I think you have the problem with Magestore_Bannerslider which is not our extension. Please contact with Magestore to solve this issue.
