### ISSUE TITLE
Cannot disable module

### ISSUE THREAD

**Issue by Tyrianad** [mageplaza/magento-2-product-slider#13]
I am trying to disable and remove the module but it looks like i cannot do it. I installed it via copy & paste instead of composer, i tried disabling it, removing references in the etc/config.php and in the setup_module table, i then run setup:upgrade and cache:flush but when i try to edit a product i get a missing file error which is related to productslider.
Am i missing something?

**Comment by GuerrillaCoder** [comment]
I have same issue.  Is anywhere listed how to remove all traces of this module?

**Comment by oviliz** [comment]
@Tyrianad / @GuerrillaCoder , have you tried https://docs.mageplaza.com/kb/uninstallation.html?
