### ISSUE TITLE
Code Compilation Stuck Up! - Incompatible argument type...

### ISSUE THREAD

**Issue by tamada1** [mageplaza/magento-2-product-slider#19]
same issue as https://github.com/mageplaza/magento-2-blog/issues/90

**Comment by oviliz** [comment]
@tamada1 , looking at your link, I've applied the fix https://github.com/mageplaza/magento-2-blog/commit/d0b7eea3b7ac33c88967600bde0b3f26e568a480 in app/code/Mageplaza/Productslider/Model/ResourceModel/Slider/Grid/Collection.php and it works.

Hopefully, this would be fixed.

PS. I'm using Magento 2.2 and it happens with both extension 1.2.2 and 1.2.3.1.
