### ISSUE TITLE
Update composer.json to install 1.2.3

### ISSUE THREAD

**Issue by rougiain** [mageplaza/magento-2-product-slider#24]
Update composer to install 1.2.3

**Comment by ninhkx** [comment]
Hi,
I am Jordi from Mageplaza.com.
Are you having problems with our extension? If yes, please explain more about your issue.
Have a nice day!

**Comment by rougiain** [comment]
When installing via composer it installs the old version with hardcoded title 1.2.2 not 1.2.3 with the fix

 

Regards

**Comment by ninhkx** [comment]
Hi, 
Thank you for the reply.
Currently, version 1.2.2 is working stable, so if you have any issue, please contact us.
We will fix it and update in the new version.
Thank you!

**Comment by imsamthomas** [comment]
We have added LICENSE file in v1.2.3. The source code is same with v1.2.2.
