### ISSUE TITLE
Cannot enter Admin Config after installing

### ISSUE THREAD

**Issue by Jimmyballantyne** [mageplaza/magento-2-product-slider#25]
### Preconditions

1. Magento: 2.2.1
2. PHP: 7
3. MySQL: 5.6.37 
4. 

### Steps to reproduce

1.  Copy Module Files
2. Run setup:upgrade, Clear Cache 
3. Login to Admin and go to Stores -> configuration

### Expected result
1. Open's settings menu

### Actual result
1 exception(s):
Exception #0 (Exception): Notice: Undefined index: id in /home/site/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63

Exception #0 (Exception): Notice: Undefined index: id in /home/site/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php on line 63
#0 /home/site/public_html/vendor/magento/module-config/Model/Config/Structure/Element/Iterator.php(63): Magento\Framework\App\ErrorHandler->handler(8, 'Undefined index...', '/home/site/...', 63, Array)
#1 /home/site/public_html/vendor/magento/module-config/Model/Config/Structure.php(146): Magento\Config\Model\Config\Structure\Element\Iterator->setElements(Array, 'default')
#2 /home/site/public_html/generated/code/Magento/Config/Model/Config/Structure/Interceptor.php(24): Magento\Config\Model\Config\Structure->getTabs()
#3 /home/site/public_html/vendor/magento/module-config/Model/Config/Structure.php(209): Magento\Config\Model\Config\Structure\Interceptor->getTabs()
#4 /home/site/public_html/generated/code/Magento/Config/Model/Config/Structure/Interceptor.php(76): Magento\Config\Model\Config\Structure->getFirstSection()
#5 /home/site/public_html/vendor/magento/module-config/Controller/Adminhtml/System/AbstractConfig.php(60): Magento\Config\Model\Config\Structure\Interceptor->getFirstSection()
#6 /home/site/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Config\Controller\Adminhtml\System\AbstractConfig->dispatch(Object(Magento\Framework\App\Request\Http))
#7 /home/site/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callParent('dispatch', Array)
#8 /home/site/public_html/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#9 /home/site/public_html/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch(Object(Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor), Object(Closure), Object(Magento\Framework\App\Request\Http))
#10 /home/site/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#11 /home/site/public_html/generated/code/Magento/Config/Controller/Adminhtml/System/Config/Index/Interceptor.php(39): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->___callPlugins('dispatch', Array, NULL)
#12 /home/site/public_html/vendor/magento/framework/App/FrontController.php(55): Magento\Config\Controller\Adminhtml\System\Config\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#13 /home/site/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#14 /home/site/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch', Array)
#15 /home/site/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#16 /home/site/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch', Array, Array)
#17 /home/site/public_html/vendor/magento/framework/App/Http.php(135): Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#18 /home/site/public_html/vendor/magento/framework/App/Bootstrap.php(256): Magento\Framework\App\Http->launch()
#19 /home/site/public_html/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#20 {main}

**Comment by Jimmyballantyne** [comment]
I've now tried uninstalling the module and reinstalling using composer but still get the same issue.

The rest of the admin works fine, just the configuration that doesn't work

**Comment by ninhkx** [comment]
Hi,
I am Jordi from Mageplaza.com
For the technical issues, please submit your ticket to mageplaza.freshdesk.com 
and provide the following information in the submit form:

- Magento temporary login details (including Back-end URL)
- Temporary SSH/ SFTP log in details (should be able to read/write pub/ var/ folders)

Our support team will look into your particular case as soon as possible.
Have a nice day!
