### ISSUE TITLE
Compilation failing on composer install

### ISSUE THREAD

**Issue by sf3ris** [mageplaza/magento-2-product-slider#28]
Hi,
After installing the package with composer i got the error:

> 
> > 
> > Mageplaza\Productslider\Model\ResourceModel\Slider\Grid\Collection
> > 		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Productslider\Model\ResourceModel\Slider\Grid\connection; File: 
> > /home/barberli/public_html/Store/vendor/mageplaza/magento-2-product-slider/Model/ResourceModel/Slider/Grid/Collection.php
> > 
> > Total Errors Count: 1
> 
>                                            
>   [Magento\Framework\Validator\Exception]  
>   Error during compilation

Had to edit the file in vendor/mageplaza/magento-2-product-slider/Model/ResourceModel/Slider/Grid/Collection.php:
Replacing the line inside the function __construct()
> $connection = null,

with : 
> \Magento\Framework\DB\Adapter\AdapterInterface $connection = null,

Just suggesting to fix the error in the composer package.
Thanks,

### Preconditions

1. Magento: 2.2.2
2. PHP: 7.1
3. MySQL: n/d
4. 

### Steps to reproduce

1.  composer require mageplaza/magento-2-product-slider
2. php bin/magento setup:upgrade
3. php bin/magento setup:di:compile

### Expected result

1. Compilation failing with following error:

> 
> > 
> > Mageplaza\Productslider\Model\ResourceModel\Slider\Grid\Collection
> > 		Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Productslider\Model\ResourceModel\Slider\Grid\connection; File: 
> > /home/barberli/public_html/Store/vendor/mageplaza/magento-2-product-slider/Model/ResourceModel/Slider/Grid/Collection.php
> > 
> > Total Errors Count: 1
> 
>                                            
>   [Magento\Framework\Validator\Exception]  
>   Error during compilation

**Comment by ninhkx** [comment]
Hi,
I am Jordi from Mageplaza.com.
Your issue has been fixed in the latest version of Product Slider extension.
Also, your edits are exactly the same as our changes.

Thank you so much for using our product.

**Comment by ninhkx** [comment]
Close due to no responses within 7 days.
