### ISSUE TITLE
Bestsellers SQL error

### ISSUE THREAD

**Issue by elpas0** [mageplaza/magento-2-product-slider#29]
When I try to create bestsellers block in cms page, i get following error:

Error filtering template: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS `t`' at line 1, query was: SELECT COUNT(*) FROM () AS `t`

### Preconditions

1. Magento: 2.2.0
2. PHP: 7.1
3. MySQL: 5.6
4. Magento in developer mode, cache disabled

### Steps to reproduce
1. Add following code to cms page 
{{block class="Mageplaza\Productslider\Block\BestSellerProducts" template="Mageplaza_Productslider::productslider.phtml" products_count="8" heading="BestSeller Products" description="Here is your new products description"}}
2. Save page
3. Refresh frontend

### Expected result
I should see bestsellers

### Actual result
I see sql error:

Error filtering template: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') AS `t`' at line 1, query was: SELECT COUNT(*) FROM () AS `t`

**Comment by Kenny1994** [comment]
Hi,
For the technical issues, please submit your ticket to https://mageplaza.freshdesk.com and provide the following information in the submit form:
- Magento temporary login details (including Back-end URL)
- Temporary SSH/ SFTP log in details (should be able to read/write pub/ var/ folders)

Our support team will look into your particular case as soon as possible.

**Comment by Tuvpt** [comment]
Your issue has been resolved at this link:
https://github.com/mageplaza/magento-2-product-slider/commit/46b1fc3afdb731eae60eb9bbb86bb5ecde16f4ec

**Comment by lobzenko** [comment]
I have same issue, downloaded last realese. Installiation used composer and manual. 

magento version 2.2.3
