### ISSUE TITLE
core package is named differently in diff modules

### ISSUE THREAD

**Issue by joelmats** [mageplaza/magento-2-product-slider#3]
### Preconditions

1. Magento: 2.1.5
2. PHP: 7.0.15
3. MySQL: 
4. 

### Steps to reproduce

1. ```sh composer require mageplaza/magento-2-product-slider```
2. ```sh composer require mageplaza/magento-2-social-login```
3. ```sh php bin/magento setup:upgrade```
4. ```sh php bin/magento setup:static-content:deploy```

### Expected result

1.  Should succeed

### Actual result

1. Exception.. mageplaza/core-m2 defines classes already defined in mageplaza/module-core

**Comment by imsamthomas** [comment]
We have changed all of our repo and fix this.
