### ISSUE TITLE
Recently Viewed slider not shown with cache enabled

### ISSUE THREAD

**Issue by elpas0** [mageplaza/magento-2-product-slider#30]
Recently Viewed slider not shown with cache enabled. If I disable it I can see products

### Preconditions

1. Magento: 2.2.0
2. PHP: 7.1
3. MySQL: 5.6
4. Magento in developer mode

### Steps to reproduce
1. Insert following code into cms page:
{{block class="Mageplaza\Productslider\Block\RecentProducts" template="Mageplaza_Productslider::productslider.phtml" products_count="8" heading="Recent Products" description="Here is your new products description" }}
2. Save page
3. Check frontend

### Expected result
I should see recently viewed products

### Actual result
Recently Viewed slider not shown with cache enabled. If I disable it I can see products

**Comment by Kenny1994** [comment]
Hi,
For the technical issues, please submit your ticket to https://mageplaza.freshdesk.com and provide the following information in the submit form:
- Magento temporary login details (including Back-end URL)
- Temporary SSH/ SFTP log in details (should be able to read/write pub/ var/ folders)

Our support team will look into your particular case as soon as possible.

**Comment by ninhkx** [comment]
Hi,
Thank you for using our extension
We are developing a new version of PS with more features. It has a cache lifetime feature. It will help you solve this problem.
We will soon release it in the future.
