### ISSUE TITLE
Error filtering template: Warning: Invalid argument supplied for foreach() in /home/user/public_html/vendor/mageplaza/magento-2-product-slider/Block/AbstractSlider.php on line 425

### ISSUE THREAD

**Issue by Jimmyballantyne** [mageplaza/magento-2-product-slider#31]
### Preconditions

1. Magento: 2.2.3
2. PHP: 7
3. MySQL: 
4. 

### Steps to reproduce

1. Upgraded to 2.2.3
2. 
3. 

### Expected result

1. Home page displays with product slider

### Actual result

1. [Screenshot, logs]

Main page  content doesn't load error message instead:
Error filtering template: Warning: Invalid argument supplied for foreach() in /home/user/public_html/vendor/mageplaza/magento-2-product-slider/Block/AbstractSlider.php on line 425

**Comment by ninhkx** [comment]
I am Jordi from Mageplaza.com.
I have tested your problem on Magento 2.2.3 and I did not have the same problem as you described.
You can update the latest version of Product Slider extension here: https://github.com/mageplaza/magento-2-product-slider and try again.
Also, you should update the latest version of Mageplaza core here: https://github.com/mageplaza/module-core

Thank you!

**Comment by ninhkx** [comment]
Closed due to no feedback within 7 days

**Comment by GreenImp** [comment]
I'm getting a very similar issue:

> Error filtering template: Warning: Invalid argument supplied for foreach() in /Users/sunshine/www/v12/vagrant-magento/magento2ce/vendor/mageplaza/magento-2-product-slider/Block/CategoryId.php on line 97

This is when adding a slider as a block in a CMS page like so:

```html
<p>{{block class="Mageplaza\Productslider\Block\CategoryId" template="Mageplaza_Productslider::productslider.phtml" products_count="8" heading="Slider Heading" category_id="9" description="Slider Description "}}</p>
```

The issue seems to be with this bit of code, /Block/CategoryId.php on lines 87 - 128:
```php
    /**
     * Get ProductIds by Category
     *
     * @return array
     */
    public function getProductIdsByCategory()
    {
        $productIds = [];
        $catIds     = $this->getSliderCategoryIds();

        foreach ($catIds as $catId) {
            $category   = $this->_categoryFactory->create()->load($catId);
            $collection = $this->_productCollectionFactory->create()
                ->addAttributeToSelect('*')
                ->addCategoryFilter($category);

            foreach ($collection as $item) {
                $productIds[] = $item->getData('entity_id');
            }
        }

        return $productIds;
    }

    /**
     * Get Slider CategoryIds
     *
     * @return array|int|mixed
     */
    public function getSliderCategoryIds()
    {
        if ($this->getData('category_id')) {
            return $this->getData('category_id');
        }
        if ($this->getSlider()) {
            $catIds = explode(',', $this->getSlider()->getCategoriesIds());

            return $catIds;
        }

        return 2;
    }
```

The `getSliderCategoryIds()` method in this case is returning a string, `"9"` on line 119:
```php
return $this->getData('category_id');
```

But in `getProductIdsByCategory()` it expects it to be an array:
```php
        $catIds     = $this->getSliderCategoryIds();

        foreach ($catIds as $catId) {
            ....
```

You could fix this by splitting the `$catIds` by commas if it's not an array. Like you're already doing in the `getSliderCategoryIds()` method `if ($this->getSlider()) {` statement, but this time inside the `getProductIdsByCategory()` method.
That way you don't have to change the output of the `getSliderCategoryIds()` method and potentially break something that is actually expecting a string:

```php
        $catIds     = $this->getSliderCategoryIds();
        $catIds = !is_array($catIds) ? split(',', $catIds) : $catIds;

        foreach ($catIds as $catId) {
            ....
```


For what it's worth, I'm using Magento 2.3, but I don't think this is version specific.

**Comment by GreenImp** [comment]
Off the back of this, I've noticed that if I fix that bug, it finds another one:

> Fatal error: Uncaught Error: Call to a member function getDisplayAdditional() on null in /magento_root/vendor/mageplaza/magento-2-product-slider/Block/AbstractSlider.php:134

```php
$display = $this->getSlider()->getDisplayAdditional();
```

It seems like there's a missing check to ensure that `getSlider()` returns something.
Changing the method to this, fixes the issue:

```php
    /**
     * @return mixed
     */
    public function getDisplayAdditional()
    {
        if(!$this->getSlider()){
            return [];
        }

        $display = $this->getSlider()->getDisplayAdditional();
        if (!is_array($display)) {
            $display = explode(',', $display);
        }

        return $display;
    }
```

**Comment by GreenImp** [comment]
And another issue is that the title doesn't show, because the `AbstractSlider->getTitle()` method sets the `$title` to the response of `$this->hasData('title')` which returns a boolean:

```php
        if ($title = $this->hasData('title')) {
            return $title;
        }
```

It needs to be:
```php
        if ($this->hasData('title')) {
            return $this->getData('title');
        }
```

**Comment by GreenImp** [comment]
@ninhkx @imsamthomas Any chance you could take a look at the issues I've raised and my pull request to fix them?

**Comment by DrakeJack** [comment]
Thank you for your contribution. 
We are considering to update it in the latest version of Product Slider.

**Comment by fheyer** [comment]
@DrakeJack 
Please solve this issue and merge the pull request by @GreenImp !
