### ISSUE TITLE
Incompatible argument type

### ISSUE THREAD

**Issue by polimex** [mageplaza/magento-2-product-slider#33]
### Preconditions

1. Magento: 2.2.3
2. PHP: 7.0.28
3. MySQL: 
4. 

### Steps to reproduce

1. Installation
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

Interception cache generation... 6/7 [========================>---]  85% 32 secs 276.0 MiBErrors during compilation:
        Mageplaza\Productslider\Model\ResourceModel\Slider\Grid\Collection
                Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Productslider\Model\ResourceModel\Slider\Grid\connection; File:
/var/www/future-home/vendor/mageplaza/magento-2-product-slider/Model/ResourceModel/Slider/Grid/Collection.php

Total Errors Count: 1

  [Magento\Framework\Validator\Exception]
  Error during compilation

**Comment by ninhkx** [comment]
Hi,
I am Jordi from Mageplaza.com
Your problem has been fixed in the latest version. Here is edited file path: https://github.com/mageplaza/magento-2-product-slider/blob/master/Model/ResourceModel/Slider/Grid/Collection.php
You can update the latest version and try again.
Thank you!

**Comment by polimex** [comment]
#composer update mageplaza/magento-2-product-slider
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Package sjparkinson/static-review is abandoned, you should avoid using it. Use p                        hpro/grumphp instead.
Generating autoload files

# php bin/magento setup:di:compile
Compilation was started.
Proxies code generation... 0/7 [>---------------------------]   0% < 1 sec 46.0                         Proxies code generation... 1/7 [====>-----------------------]  14% < 1 sec 50.0                         Repositories code generation... 1/7 [====>-----------------------]  14% < 1 sec                         50.0 MiB
Interception cache generation... 6/7 [========================>---]  85% 29 secs 276.0 MiBErrors during compilation:
        Mageplaza\Productslider\Model\ResourceModel\Slider\Grid\Collection
                Incompatible argument type: Required type: \Magento\Framework\DB\Adapter\AdapterInterface. Actual type: \Mageplaza\Productslider\Model\ResourceModel\Slider\Grid\connection; File:
/var/www/future-home/vendor/mageplaza/magento-2-product-slider/Model/ResourceModel/Slider/Grid/Collection.php

Total Errors Count: 1


  [Magento\Framework\Validator\Exception]
  Error during compilation


setup:di:compile

**Comment by polimex** [comment]
After manual update of the fille , all is working well

**Comment by ninhkx** [comment]
Hi,
We will fix it in #composer.
Due the issue has been solved, I will close this issue.

**Comment by dhrumin44** [comment]
Hello @ninhkx ,

I can't find this file https://github.com/mageplaza/magento-2-product-slider/blob/master/Model/ResourceModel/Slider/Grid/Collection.php

Can you please provide proper file path.
