### ISSUE TITLE
Bestseller Slider shows not visible Products

### ISSUE THREAD

**Issue by Waldemar-Denke** [mageplaza/magento-2-product-slider#34]
Magento 2.2.2
PHP 7

The Widget shows Not visible Products. Products, witch were bought over configurable Products. So i'm getting Products with 404 link.

Can you add visibility filter to the collection? Or is there an other setting i don't see?

**Comment by Tuvpt** [comment]
Your issue has been resolved at this link:
46b1fc3

**Comment by Waldemar-Denke** [comment]
Thx. it works. Please merge to master.
