### ISSUE TITLE
Price not updated when currency is changed on frontend

### ISSUE THREAD

**Issue by wester9208** [mageplaza/magento-2-product-slider#36]
### Preconditions

1. Magento: 2.1.9
2. PHP: 7.0
3. MySQL: 5.7.22
4. 

### Steps to reproduce

1. place slider on any page
2. Next change the currency on frontend

### Expected result

1. Should update the prices to current currency which is choosen

### Actual result
1. showing old currency and not the updated currency

**Comment by Tuvpt** [comment]
We can not reproduce this problem.
However, you can please flush page cache and browser cache then check it again

**Comment by gixid192** [comment]
Close due to no response within 7 days.
