### ISSUE TITLE
[Question] Add to cart with ajax

### ISSUE THREAD

**Issue by jahicDario** [mageplaza/magento-2-product-slider#37]
Is there a easy way to set ajax functionality for add to cart button within your module? 
Thanks.

**Comment by Tuvpt** [comment]
Unfortunately, the current version has not supported this function yet. I'm so sorry for that. 
However, I will surely note it to our developer to consider about developing it in the future so please look forward to this

**Comment by Tuvpt** [comment]
Close due to no response within 7 days.
