### ISSUE TITLE
does it work on version M 2.2.3?

### ISSUE THREAD

**Issue by qurtopianodesign** [mageplaza/magento-2-product-slider#40]
Hi,
I installed the plugin on a custom theme.
version 2.2.3 but the products do not appear on the slider ... Is there a problem with configurable products?
http://5.94.76.53:8888/site_myfashionhit_2018/borsa-comme-des-garcons-rosa-e-gialla-comme-des-garcons-wallet-pe-17.html

**Comment by bdtrung** [comment]
Hi,
Regarding your problem, I can not reproduce your problem on our local.
So please make sure you have installed the latest version of Core module, Product Slider module and do the same steps in the user guide at this link: https://docs.mageplaza.com/product-slider-m2/

Thank you!

**Comment by Tuvpt** [comment]
Close due to no response within 7 days.
