### ISSUE TITLE
can't work

### ISSUE THREAD

**Issue by benyang2015** [mageplaza/magento-2-product-slider#41]
### Preconditions

1. Magento: 2.2.5
2. PHP: 7.1
3. MySQL: 5.7
4. 

### Steps to reproduce

1. install on local，on the frontend, can't see any product about new and bestseller
2. everything config fine
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by saunptit97** [comment]
I'm Roger from Mageplaza.com. I will assist you. Please set your new products and best seller product http://prntscr.com/kvmdy4 then tell me the result. Thank you!

**Comment by benyang2015** [comment]
install on the new project,not any third plugin
magento 2.2.5

**Comment by Tuvpt** [comment]
please run reindex command: **php bin/magento index:reindex** then select the reload data button in the admin dashboard

**Comment by Tuvpt** [comment]
Close due to no response within 7 days.
