### ISSUE TITLE
Call to a member function getDisplayAdditional()

### ISSUE THREAD

**Issue by OnlyDream** [mageplaza/magento-2-product-slider#42]
When trying to use the current code 

  <block class="Mageplaza\Productslider\Block\OnSaleProduct" name="product.slider.newproduct" template="productslider.phtml">
                                <arguments>
                                    <argument name="products_count" xsi:type="number">8</argument>
                                    <argument name="margin" xsi:type="string">5</argument>
                                    <argument name="heading" xsi:type="string">New Products</argument>
                                    <argument name="description" xsi:type="string">Here is your new products  description </argument>
                                </arguments>
                            </block>

in the page the current error appears.

`Fatal error: Uncaught Error: Call to a member function getDisplayAdditional() on null`

On file \vendor\mageplaza\magento-2-product-slider\Block\AbstractSlider.php on line 132

**Comment by OnlyDream** [comment]
The problem here is the $this->getSlider() is null when trying to call the getDisplayAdditional , and i wanna call the slider in phtml , and i can't like that.

**Comment by saunptit97** [comment]
Please create a ticket. We will support you.

**Comment by Tuvpt** [comment]
Close due to no response within 7 days.
