### ISSUE TITLE
Recently Viewed slider not shown with cache enabled

### ISSUE THREAD

**Issue by kpalRave** [mageplaza/magento-2-product-slider#45]
**ANY UPDATE REGARDNG THIS ?????**

 
@ninhkx commented ---->>

Hi,
Thank you for using our extension
We are developing a new version of PS with more features. It has a cache lifetime feature. It will help you solve this problem.
We will soon release it in the future.

**Comment by gixid192** [comment]
duplicated https://github.com/mageplaza/magento-2-product-slider/issues/46
