### ISSUE TITLE
Slider not shown with cache enabled ????

### ISSUE THREAD

**Issue by kpalRave** [mageplaza/magento-2-product-slider#46]
ANY UPDATE REGARDNG THIS ?????

@ninhkx commented ---->>

Hi,
Thank you for using our extension
We are developing a new version of PS with more features. It has a cache lifetime feature. It will help you solve this problem.
We will soon release it in the future.

### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by tallcoder** [comment]
I'm currently having this problem, so I'm guessing it's not resolved yet.
