### ISSUE TITLE
What are available short code settings?

### ISSUE THREAD

**Issue by sts-ryan-holton** [mageplaza/magento-2-product-slider#52]
Hi, I'm using the products carousel via the shortcode method: https://docs.mageplaza.com/product-slider-m2/#cms-page-cms-static-block

I was wondering what settings there are available that I can add on here? e.g: I'd like to show 2 `.owl-item` divs, how can I do this? I've tried changing: `products_count="2"` with little luck, it still shows by default 3 items, I want to show say 4 items at any one time and then I can scroll. My shortcode is:

```
{{block class="Mageplaza\Productslider\Block\CategoryId" template="Mageplaza_Productslider::productslider.phtml" products_count="2" heading="Products carousel" category_id="3, 5" description="Products carousel"}}
```

I guess I need to somehow use: **Max Items Slider** as a setting on my shortcode to choose how many items display at different viewports

/cc @DrakeJack

**Comment by sts-ryan-holton** [comment]
**UPDATE:**

I have found this page: http://docs.mageplaza.com/product-slider-m2/product-slider-options.html which lists out options. I have implemented some of these options for creating a responsive slider, in particular: `items="4"` should be showing 4 items in my carousel, but it's only showing 3.

Also with `merge="1"` set to **1** it doesn't appear to merge on smaller devices, it's still displaying 3? Do these options work? What am I missing, thanks.

```
{{block class="Mageplaza\Productslider\Block\CategoryId" template="Mageplaza_Productslider::productslider.phtml" products_count="8" heading="Products carousel" category_id="3, 5" description="Products carousel" responsive="1" items="4" loop="1" merge="1"}}
```

**Comment by sts-ryan-holton** [comment]
`items="4"` doesn't seem to work

**Comment by bdtrung** [comment]
I've tried your code on my local and it seems like works very well.
For the responsive problem, please try to config in the Store -> Configuration -> Mageplaza Extensions -> Product Slider -> Slider Design Configuration tab -> Responsive (http://prntscr.com/mpp31n).
If it still not works, please create a ticket for us via this link: https://mageplaza.freshdesk.com/support/tickets/new
We'll provide you the best support!

Thanks a lot!

**Comment by sts-ryan-holton** [comment]
@bdtrung Thanks for your reply, I'm using a short code in my page and not using any configuration options through the backend. I've looked through the code and it appears that specifying `items="x"` on my short code doesn't appear to actually get pulled through becuase in the phtml file it's getting block options, and I'm not sure whether a short code is a block.

**Comment by bdtrung** [comment]
Please try to the configuration in the backend like my instruction, it's will very easier and simpler to config the slider.

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
