### ISSUE TITLE
Random products

### ISSUE THREAD

**Issue by Zyles** [mageplaza/magento-2-product-slider#53]
Ability to show random products using conditions. For example fetch 10 random products from category X.

**Comment by sts-ryan-holton** [comment]
@Zyles  I think you have to specify `products_count="X"`, however I myself am having mixed results using the shortcode tag for another issue here: https://github.com/mageplaza/magento-2-product-slider/issues/52, let's hope we can get these resolved quickly

**Comment by bdtrung** [comment]
To show the product as your example, you can create a rule with the type is Select by Category (http://prntscr.com/mpoyuv), choose the Category which you want to show and at the Design tab, you can set the number of the product will showing (http://prntscr.com/mpozpd).

**Comment by Zyles** [comment]
When inserting widget on a page, what selection of these should I choose to get random products from a category?

![mageplaza_widget](https://user-images.githubusercontent.com/1741593/53841139-57ae4e80-3f9c-11e9-9a8b-20207cfddc03.png)

**Comment by bdtrung** [comment]
Regarding  your question, the Product Slider module does not support the slider as your requirement by using Widget, you only can choose the random product from a category by add Slider in Content -> Product Slider -> Manage Slider

**Comment by Zyles** [comment]
Okay that kinda sucks because I need a widget with random products from a specific category.

**Comment by bdtrung** [comment]
You can use the block code to add it.
Please refer to this [link](https://github.com/mageplaza/magento-2-product-slider/issues/49)

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
