### ISSUE TITLE
Custom position with widget

### ISSUE THREAD

**Issue by Zyles** [mageplaza/magento-2-product-slider#54]
I would like to create a widget on CMS page or a custom block.

Does not seem to be possible.

**Comment by bdtrung** [comment]
Hi,
To create a product slider by using widget you can use the following code: 
`{{widget type="Mageplaza\Productslider\Block\Widget\Slider" title="New Products" products_count="5" product_type="new"}}`
Here is the list of product type: [list type](http://prntscr.com/mtu18n)
Or you can follow this guide to create a slider via Widget: [Product Slider guide](https://docs.mageplaza.com/product-slider-m2/)

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
