### ISSUE TITLE
Slider position option

### ISSUE THREAD

**Issue by snoroozi** [mageplaza/magento-2-product-slider#55]
I have several sliders on my homepage. Can you please add sort order for different sliders?

Also, recently viewed slider doesn't seem to work in my case.

**Comment by DrakeJack** [comment]
I'm Drake from Mageplaza and I'm really sorry for the late reply.
Our Product Slider extension doesn't have the Sort Order feature.
I really appreciate your feedback, we will consider developing it in the future.

About recently viewed slider, I need to check on your site to find out the solution.
Please visit [https://mageplaza.freshdesk.com/support/home] and create a ticket and I'll help you solve the problem.

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
