### ISSUE TITLE
Mageplaza slider when included via layout xml, throws "Fatal error: Uncaught Error: Call to a member function getDisplayAdditional() on null " error

### ISSUE THREAD

**Issue by gokrish7** [mageplaza/magento-2-product-slider#56]
### Steps to reproduce

1. Add the following Mageplaza Slider in a layout xml like below (ex catalog_product_view.xml)
`<block class="Mageplaza\Productslider\Block\MostViewedProducts" name="product2.slider.category.new" template="Mageplaza_Productslider::productslider.phtml">
                    <arguments>
                        <argument name="products_count" xsi:type="number">8</argument>
                        <argument name="margin" xsi:type="string">5</argument>
                        <argument name="title" xsi:type="string">Recommended Accessories</argument>
                    </arguments>
                </block>`
2. Refresh cache and check Product page (for ex) .
3. See if you are able to get the slider appear properly

 

### Expected result
1.  No error should occur and the slider should work properly

### Actual result
On checking the storefront shows the error
_**Fatal error: Uncaught Error: Call to a member function getDisplayAdditional() on null**_
Log:
Fatal error: Uncaught Error: Call to a member function getDisplayAdditional() on null in /var/www/html/app/code/Mageplaza/Productslider/Block/AbstractSlider.php:133 Stack trace: #0 /var/www/html/app/code/Mageplaza/Productslider/Block/AbstractSlider.php(154): Mageplaza\Productslider\Block\AbstractSlider->getDisplayAdditional() #1 /var/www/html/app/code/Mageplaza/Productslider/view/frontend/templates/productslider.phtml(49): Mageplaza\Productslider\Block\AbstractSlider->canShowReview() #2 /var/www/html/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/html/a...') #3 /var/www/html/vendor/magento/framework/View/Element/Template.php(271): Magento\Framework\View\TemplateEngine\Php->render(Object(Mageplaza\Productslider\Block\MostViewedProducts\Interceptor), '/var/www/html/a...', Array) #4 /var/www/html/vendor/magento/framework/View/Element/Template.php(301): Magento\Framework\View\Element\Template->fetchView('/var/www/html/a...') #5 /var/www/html/vendor/magento/framework/View/Element/AbstractBlock.php( in /var/www/html/app/code/Mageplaza/Productslider/Block/AbstractSlider.php on line 133

**Comment by saunptit97** [comment]
I'm Roger from Mageplaza. Please try to edit in the file Mageplaza\Productslider\Block\AbstractSlider.php http://prntscr.com/n9yoq0.

**Comment by gokrish7** [comment]
Hi Roger, I was not able to get the issue fixed by your change. It requires more than that which I have updated in my PR. Please review that once.
