### ISSUE TITLE
On adding multiple sliders via layout xml, same sliderId is persisted and only one slider is shown.

### ISSUE THREAD

**Issue by gokrish7** [mageplaza/magento-2-product-slider#57]
### Steps to reproduce
Add the following Mageplaza Slider in a layout xml like below (ex catalog_product_view.xml)
`<block class="Mageplaza\Productslider\Block\MostViewedProducts" name="product2.slider.category.new" template="Mageplaza_Productslider::productslider.phtml"> <arguments> <argument name="products_count" xsi:type="number">8</argument> <argument name="margin" xsi:type="string">5</argument> <argument name="title" xsi:type="string">Recommended Accessories</argument> </arguments> </block>`

1. Add the same block again, like below:

`<block class="Mageplaza\Productslider\Block\MostViewedProducts" name="product2.slider.category.new" template="Mageplaza_Productslider::productslider.phtml"> <arguments> <argument name="products_count" xsi:type="number">8</argument> <argument name="margin" xsi:type="string">5</argument> <argument name="title" xsi:type="string">Recommended Accessories</argument> </arguments> </block>`

2. Note that you have 2 sliders now.
3. Refresh cache and check Product page (for ex) .
4. See if you are able to get the sliders appear properly

### Expected result
Both sliders should be shown and unique slider id is assigned.

### Actual result
Only one slider is shown as the same slider id is assigned to both.

**Comment by saunptit97** [comment]
I'm Roger from Mageplaza. 
The current version has not supported multiple slider blocks. I'm so sorry about that. 
However, I will surely note it to our developer to consider developing it in the future so please look forward to this. Thank you very much for your feedback.

**Comment by gokrish7** [comment]
The main issue is that the same "sliderId" gets assigned for the sliders if we use multiple ones. So I have created a new PR in which I have set the option of setting the sliderId as arguments.

`<block class="Mageplaza\Productslider\Block\MostViewedProducts" name="product2.slider.category.new" template="Mageplaza_Productslider::productslider.phtml"> <arguments> <argument name="products_count" xsi:type="number">8</argument> <argument name="margin" xsi:type="string">5</argument> <argument name="title" xsi:type="string">Recommended Accessories</argument>**<argument name="sliderId" xsi:type="string">most_viewed_slider</argument>** </arguments> </block>`

By this way you can assign a different slider id and use the same block again.
Please check my PR that contains additional options like showCart, showReview, showPrice etc too

**Comment by extremeskillz** [comment]
Same issue. I'm running Magento 2.3.2. Please fix.

**Comment by Tuvpt** [comment]
@gokrish7 @extremeskillz  Thank you for your interest in our extension.
The issue has been resolved in the latest version. However,you should change the **name** parameter of the block when use the snippet code to apply many sliders on the same page.
Ex: 
`<block class="Mageplaza\Productslider\Block\MostViewedProducts" name="product.slider.mostview1" template="Mageplaza_Productslider::productslider.phtml">`

`<block class="Mageplaza\Productslider\Block\MostViewedProducts" name="product.slider.mostview2" template="Mageplaza_Productslider::productslider.phtml">`
