### ISSUE TITLE
Slider title shown as " 1 " instead of actual title.

### ISSUE THREAD

**Issue by gokrish7** [mageplaza/magento-2-product-slider#58]
### Steps to reproduce
1. Add the following Mageplaza Slider in a layout xml like below (ex catalog_product_view.xml)
`<block class="Mageplaza\Productslider\Block\MostViewedProducts" name="product2.slider.category.new" template="Mageplaza_Productslider::productslider.phtml"> <arguments> <argument name="products_count" xsi:type="number">8</argument> <argument name="margin" xsi:type="string">5</argument> <argument name="title" xsi:type="string">Recommended Accessories</argument> </arguments> </block>`

2. Since title is mentioned in the argument, the expectation is to see it in storefront.
3. Refresh cache and check Product page (for ex) .
4. See if you are able to get the slider appear properly with appropriate title given in params

### Expected result
Title provided in argument(param) should be used and be displayed.

### Actual result

"1" is shown as the title instead of the title given in arguments.

<img width="1313" alt="Screen Shot 2019-04-10 at 2 19 24 PM" src="https://user-images.githubusercontent.com/19623448/55865308-afdc0000-5b9b-11e9-96db-47cd69b5b7b2.png">

**Comment by saunptit97** [comment]
I'm Roger from Mageplaza. Please try to edit in the file Mageplaza\Productslider\Block\AbstractSlider.php http://prntscr.com/n9yoq0.

**Comment by gokrish7** [comment]
This issue is because the current logic is returning hasData('title') instead of getData('title').
The hasData('title') will return boolean true and thus 1 is returned.
