### ISSUE TITLE
Allow for setting position to 'custom' in slider options

### ISSUE THREAD

**Issue by SomeGeek** [mageplaza/magento-2-product-slider#61]
Allow for setting position to 'custom' when editing a slider. It shouldn't place the slider at all, but leave placement up to the developer. Right now, a slider is injected at a place I don't want, and there seems to be no way to remove it using layout XML.

This:

```xml
<referenceBlock name="productslider.home.index.top" remove="true" />
<referenceBlock name="productslider.home.index.bottom" remove="true" />
<referenceBlock name="productslider.content.top" remove="true" />
<referenceBlock name="productslider.content.bottom" remove="true" />
```

doesn't remove it at least.

I want to have full control of exacly _where_ I put the slider. I need it only at one specific place.

**Comment by SomeGeek** [comment]
Thanks for your response, however, there is no 'custom products' under 'select slider'. 

And again, the question is about not placing the widget by the module itself. I tried to set the location parameter of the specified slider to 'NULL' in the database, which gave me:

```Exception #0 (Exception): Notice: Undefined offset: 1 in [...]/vendor/mageplaza/module-banner-slider/Observer/AddBlock.php```

Probably related to this issue: https://github.com/mageplaza/magento-2-banner-slider/pull/30

And for the 'custom' admin option:

https://github.com/mageplaza/magento-2-banner-slider/pull/31/commits

So, I think it's easy to implement. (From what I can see, bannerslider and product-slider codebase share a lot)

**Comment by bdtrung** [comment]
We will look into this problem and update it soon.
Thanks so much!

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
