### ISSUE TITLE
Insert custom products slider

### ISSUE THREAD

**Issue by SomeGeek** [mageplaza/magento-2-product-slider#62]
Make it possible to insert a slider containing custom products. Right now, there is no way to select a specific slider ID using layout code.

For example:

```xml
<block class="Mageplaza\Productslider\Block\CustomProducts" name="some.custom.product.slider" template="productslider.phtml">
    <arguments>
        <argument name="slider_id" xsi:type="number">1</argument>
    </arguments>
</block>
```

**Comment by bdtrung** [comment]
Thanks for your contributions. We will look into this issue and update it in the future when possible.
Again, thanks so much!

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
