### ISSUE TITLE
  Error during compilation 

### ISSUE THREAD

**Issue by nasouhmr** [mageplaza/magento-2-product-slider#63]
### Preconditions

1. Magento: 2.3.1
2. PHP:  7.2.12 

### Steps to reproduce

1. Upload Mageplaza product slider module
2. php bin/magento setup:upgrade
3. php bin/magento setup:di:compile

### Expected result

1. Successful compile

### Actual result

1.  Mageplaza\Productslider\Block\Widget\Slider
                Incompatible argument type: Required type: \Magento\Catalog\Model\ProductRepository. Actual type: array; File:
/app/code/Mageplaza/Productslider/Block/Widget/Slider.php

        Mageplaza\Productslider\Block\BestSellerProducts
                Incompatible argument type: Required type: \Magento\Catalog\Model\ProductRepository. Actual type: array; File:
/app/code/Mageplaza/Productslider/Block/BestSellerProducts.php

        Mageplaza\Productslider\Block\CategoryId
                Incompatible argument type: Required type: \Magento\Catalog\Model\ProductRepository. Actual type: array; File:
/app/code/Mageplaza/Productslider/Block/CategoryId.php

        Mageplaza\Productslider\Block\MostViewedProducts
                Incompatible argument type: Required type: \Magento\Catalog\Model\ProductRepository. Actual type: array; File:
/app/code/Mageplaza/Productslider/Block/MostViewedProducts.php

        Mageplaza\Productslider\Block\RecentProducts
                Incompatible argument type: Required type: \Magento\Catalog\Model\ProductRepository. Actual type: array; File:
/app/code/Mageplaza/Productslider/Block/RecentProducts.php

        Mageplaza\Productslider\Block\WishlistProducts
                Incompatible argument type: Required type: \Magento\Catalog\Model\ProductRepository. Actual type: array; File:
/app/code/Mageplaza/Productslider/Block/WishlistProducts.php

Total Errors Count: 6

**Comment by DrakeJack** [comment]
I'm Drake and I'll assist you in this issue.
For the problem you reported, I'm not sure how to replicate it so please let me know the version of Magento and the theme you are using.
I'll test and provide you the solution soon.
