### ISSUE TITLE
No Products Displayed

### ISSUE THREAD

**Issue by killday** [mageplaza/magento-2-product-slider#64]
The Slider is loaded but there is no products. Nor New products or featured
![image](https://user-images.githubusercontent.com/6714294/67872062-4d435500-fb29-11e9-969d-edb3c5d85618.png)

### Preconditions

1. Magento: 2.2.0
2. PHP: 7.1.13
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by padhu1980** [comment]
I am also having this issue....

**Comment by bdtrung** [comment]
Hi,
Regarding this problem, please make sure your product asset as a new product at [here](http://i.imgur.com/6vMv97U.png).

**Comment by padhu1980** [comment]
yes, i could see now....Thanks

**Comment by bdtrung** [comment]
For these type, you need to have the product at [here](http://i.imgur.com/qencIPL.png)

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
