### ISSUE TITLE
Cannot install through composer - cannot require itself in its composer.json

### ISSUE THREAD

**Issue by sts-ryan-holton** [mageplaza/magento-2-product-slider#65]
Looks like trying to install the latest version of this package is broken through composter: `composer require mageplaza/magento-2-product-slider`

I get the following error:

`Root package 'mageplaza/magento-2-product-slider' cannot require itself in its composer.json
Did you accidentally name your root package after an external package?`

**Comment by Tuvpt** [comment]
Please describe your issue more clearly. We cannot reproduce that problem.
Make sure you run the command in the magento root directory

**Comment by ninhkx** [comment]
Close due to no response within 7 days.
