### ISSUE TITLE
Getting Error Class Mageplaza\Productslider\Observer\AddBlock does not exist

### ISSUE THREAD

**Issue by hemantsingh1209** [mageplaza/magento-2-product-slider#66]
I'm Using Magento 2.3
I just download Product slider of Mageplaza and setup it manually as code file structure. 
I have got 2 issue after setup.

 `1. Class Mageplaza\Productslider\Observer\AddBlock does not exist at home page`
 `2. In Admin panel when i click on Manage Slider, Page not opened and redirect to dashboard with error "Invalid security or form key. Please refresh the page."`

I have increase **max_input_vars = 100000**, but error not resolve.  Please solve why this error occur.

Please find error in attached image for better understanding.
 
1. Admin Panel issue.
![screencapture-127-0-0-1-m2dev-admin-admin-dashboard-index-key-b552b494000e9d97c4940722baa15d1a20e766cd08a436e9dbd9dc702d191557-2019-11-27-11_26_54](https://user-images.githubusercontent.com/19988483/69697624-fb322700-1108-11ea-9ffe-e7254db33f59.png)

2. Frontend index page issue.

![screencapture-127-0-0-1-m2dev-2019-11-27-11_26_04](https://user-images.githubusercontent.com/19988483/69697626-fb322700-1108-11ea-94b3-a5add7e6f442.png)

**Comment by bdtrung** [comment]
Hi,
Please make sure you've installed our Core module.
You can download it at [here](https://github.com/mageplaza/module-core).

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
