### ISSUE TITLE
Products images are displaying in small size

### ISSUE THREAD

**Issue by thehasanhashmi** [mageplaza/magento-2-product-slider#67]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. Mageplaza

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. It should show all product the products properly.

### Actual result

1. images of products are displaying in small size
[](url)

**Comment by bdtrung** [comment]
Hi,
Could you provide some screenshots?
We've tested on our local but everything still working well.

**Comment by bdtrung** [comment]
Close due to no response within 7 days.
