### ISSUE TITLE
Wrong Slider Title and description

### ISSUE THREAD

**Issue by hetramjanghu** [mageplaza/magento-2-product-slider#68]
### Preconditions

1. Magento: 2.3.3
2. PHP: 7.2
3. MySQL: 5.7

### Steps to reproduce

1. add featured product slider using widget on home page
2. add another featured product slider using widget on home page (change title and description)

### Expected result

1. There should be two slider with different Title and description
2. Generated HTML id for both slider should be same

 ### Actual result
1.  Only first slider working and has given title and description
2.  Both slider have same HTML id, Title and description
3.  second slider not working (only showing title and description)
4. OWL not initialized in second slider, so the div that contains class "owl-carousel" is hidden (display:none;)

**Comment by bdtrung** [comment]
Hi,
Regarding your problem, since you are using the widget for both sliders so they have the same ID.
That's why OWL can not render the second slider.
Please using "Manage slider" to add slider if you want to show 2 or more sliders on a page.

**Comment by hetramjanghu** [comment]
but that's not the write way to initialize owl.
we can generate dynamic class and do same thing using class.

**Comment by bdtrung** [comment]
Currently, we are using ID so this is happening.
We will update this soon in the future.
Thanks.

**Comment by hetramjanghu** [comment]
@bdtrung Thank You !!
