### ISSUE TITLE
Something went wrong while saving the Slider. Class Zend_Serializer_Adapter_PhpSerialize does not exist

### ISSUE THREAD

**Issue by lecampos** [mageplaza/magento-2-product-slider#69]
### Preconditions

1. Magento: 2.3
2. PHP: 7.3
3. MySQL: 
4. 

### Steps to reproduce

1. 
2.  Error whe saving a new slider
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

![image](https://user-images.githubusercontent.com/20343734/70362791-ca11cf00-184b-11ea-97f7-2df73da80a6d.png)

**Comment by toandt98** [comment]
This error is due to Magento 2.3 no longer using Zend_Serializer_Adapter_PhpSerialize.
On the branch master of our module do not use this class so it may be used in another module.
Try to find where it is used and delete it to fix the problem.

**Comment by lecampos** [comment]
Great! I have found it but it is in the Core extension:

https://github.com/mageplaza/module-core/blob/master/Helper/AbstractData.php#L37

I have deleted but now anything is working, any suggestions?

Thanks for the support!!

**Comment by lecampos** [comment]
I can fix te problem, I have changed the line https://github.com/mageplaza/module-core/blob/master/Helper/AbstractData.php#L37
 
`use Zend_Serializer_Adapter_PhpSerialize;`

with:

`use Magento\Framework\Serialize\Serializer\Serialize;`

and line https://github.com/mageplaza/module-core/blob/master/Helper/AbstractData.php#L331

` return $this->objectManager->get(Zend_Serializer_Adapter_PhpSerialize::class);`

with:

` return $this->objectManager->get(Serialize::class);`

and the error is not displayed anymore. But if I want to add the silider using the menu, it is not displayed at the fronstore, it is not until I added as CMS block in home page for example that I see it, do I am missing something?

Thanks again!

**Comment by toandt98** [comment]
Hello,
I greatly admire your knowledge, it is absolutely correct.

As for the problem of adding the slider using the menu, I don't understand what you mean.
Can you help me understand it better? (great if there are illustrations)
I would be glad to help you.

Best Regards!

**Comment by lecampos** [comment]
thank you for your answer. The problem is that if I add the product slider following the tutorial:
![image](https://user-images.githubusercontent.com/20343734/70539358-33822e00-1b29-11ea-9e9b-43270a61a086.png)
The frontstore does display any product banner, not even the title of the banner

I have to add it in the CMS content:
![image](https://user-images.githubusercontent.com/20343734/70539533-76440600-1b29-11ea-84e3-fbbe5179666e.png)
in order to see something like this in my frontstore:
![image](https://user-images.githubusercontent.com/20343734/70539587-878d1280-1b29-11ea-9151-b5591f49d390.png)
Is there some strategy that I can follow to discover the bug?

Thanks again for your support

**Comment by toandt98** [comment]
Thanks for your feedback, I now understand the problem.

Please try debugging in the file: `Mageplaza/Productslider/Observer/AddBlock.php`
This is the file that locates the block and renders the HTML

If the problem still exists, please create a ticket at https://mageplaza.freshdesk.com/
so we can assist you with the problem quickly.

Thank you very much!

**Comment by toandt98** [comment]
Close due to no response within 7 days.
