### ISSUE TITLE
Recently viewed product not showing in NOT LOGGED IN customers

### ISSUE THREAD

**Issue by purvi99** [mageplaza/magento-2-product-slider#72]
### Preconditions

1. Magento: 
2. PHP: 
3. MySQL: 
4. 

### Steps to reproduce

1. 
2. 
3. 

### Expected result

1. 

### Actual result

1. [Screenshot, logs]

**Comment by toandt98** [comment]
Hello,

Currently, we realized that the sliders using the recently viewed products are having problems with the cache.
So for now maybe you have to wait for the next upgrade for our developers to test and upgrade it.

During this time, you can refer to the widget to display recently viewed products of Magento. You can refer to the video below:
https://toandh-mageplaza.tinytake.com/tt/NDM4Njg0OV8xMzg1MTM5Mg
But the limitation of this Magento's default feature is that it can only show blocks.

Hope you understand and sympathize!
Best Regards,
​Uri
