### ISSUE TITLE
Currency on homepage getting cached and it only works after flushing the cache

### ISSUE THREAD

**Issue by syed-netable** [mageplaza/magento-2-product-slider#76]
Hi @Tuvpt 

I have noticed that you have fixed the currency issue in this commit id - 443573286352b512d9c7b215060687980bbb9748

And I have updated the module to utilize this fix. But it is getting cached 

For example, if my store is set to Australian dollar by default it loads in AUD
And changing the currency doesn't load my other currency USD

I need to flush the cache again and reload the page to see the USD

Hope you understood what I mean

Best Regards,
Syed

**Comment by Tuvpt** [comment]
The current version has not yet applied those edits. We will be adding it in an upcoming version

**Comment by syed-netable** [comment]
Thank you @Tuvpt 
Do you have an ETA for this update?

**Comment by syed-netable** [comment]
Hi @Tuvpt 
Any progress on this issue?

**Comment by Tuvpt** [comment]
This issue has been fixed in this commit 4435732
