### ISSUE TITLE
OnSale Product Block taking long time

### ISSUE THREAD

**Issue by ssmalhi** [mageplaza/magento-2-product-slider#83]
### Summary (*)
The code in the OnSaleProduct block for the collection isn't optimized at all. It iterates the whole catalog to find the special price within the product. We have added the OnSale Block on our homepage and it was taking a long long time to load and the 504 timeouts is displayed mostly when cache is refreshed.

### Examples (*)
public function getProductCollection()
    {   
        $date       = strtotime($this->_dateTimeStore->gmtDate());
        $collection = $this->_productCollectionFactory->create()->addAttributeToSelect('*');
        $productIds = [];

        foreach ($collection as $product) { $logger->debug('sss before ++++');
            if ($product->getTypeId() === 'configurable' && $product->getVisibility() != 1) {
                $_children = $product->getTypeInstance()->getUsedProducts($product);
                foreach ($_children as $child) {
                    $specialPrice = (float) $child->getSpecialPrice();
                    if ($specialPrice) {
                        if ($specialPrice < ((float) $child->getPrice())) {
                            $fromDate = strtotime($child->getSpecialFromDate());
                            if (!is_null($child->getSpecialToDate())) {
                                $toDate = strtotime($child->getSpecialToDate());
                                if ($toDate > $date) {
                                    $productIds[] = $product->getId();
                                }
                            } else {
                                if ($fromDate < $date) {
                                    $productIds[] = $product->getId();
                                }
                            }
                        }
                    }
                }
            } elseif ($product->getTypeId() === 'simple' && $product->getVisibility() != 1) {
                $specialPriceSp = (float) $product->getData('special_price');
                if ($specialPriceSp) {
                    if ($specialPriceSp < ((float) $product->getPrice())) {
                        $fromDateSp = strtotime($product->getSpecialFromDate());
                        if (!is_null($product->getSpecialToDate())) {
                            $toDateSp = strtotime($product->getSpecialToDate());
                            if ($toDateSp > $date) {
                                $productIds[] = $product->getId();
                            }
                        } else {
                            if ($fromDateSp < $date) {
                                $productIds[] = $product->getId();
                            }
                        }
                    }
                }
            }
        }

        $collectionClone = $this->_productCollectionFactory->create()->addIdFilter($productIds);
        $collectionClone->addMinimalPrice()
            ->addFinalPrice()
            ->addTaxPercents()
            ->addAttributeToSelect('*')
            ->addStoreFilter($this->getStoreId())->setPageSize($this->getProductsCount());

        return $collectionClone;
    }
### Proposed solution
public function getProductCollection()
    {
        $productCollection = $this->_productCollectionFactory->create();

        $productCollection
            ->addMinimalPrice()
            ->addFinalPrice()
            ->addTaxPercents()
            ->addStoreFilter($this->getStoreId())
            ->addAttributeToFilter('visibility', ['neq' => 1])
            ->addAttributeToFilter('status', 1)
            ->addAttributeToSelect('name')
            ->addAttributeToSelect('image')
            ->addAttributeToSelect('small_image')
            ->addAttributeToSelect('thumbnail')
            ->addAttributeToSelect('special_from_date')
            ->addAttributeToSelect('special_to_date')
            ->addAttributeToFilter('special_price', ['gt' => 0])
            ->addAttributeToSort(
                'minimal_price',
                'asc'
            )
            ->setPageSize($this->getProductsCount());

        $productCollection->getSelect()->where(
            'price_index.final_price < price_index.price'
        );

        return $productCollection;
    }

**Comment by ssmalhi** [comment]
@haitv282

**Comment by Hant186** [comment]
Hello,

I am Uri from Mageplaza Support Team.

On behalf of Mageplaza, I want to say thank you for your great contribution. Support from amazing customers like you helps our business grow and evolve thanks to your helpful feedback.

We will consider making it more readily available in the next versions of the Product Slider. Please feel welcome to reach out to me with any questions/issues. I would be more than happy to help! 
Thanks again for your valuable feedback and significant contribution. Happy New Year!

Best Regards,
Uri
