### ISSUE TITLE
Minicart does not get updated on click of add to cart button on product slider

### ISSUE THREAD

**Issue by syed-netable** [mageplaza/magento-2-product-slider#85]
### Preconditions (*)
Magento2.3.3
PHP7.2
Nginx 1.14
Mageplaza Product slider  - "version": "2.0.8"  (Copied from composer)

### Steps to reproduce (*)
Please disable redirect **product to the cart** when product is added
Please create a product slider on the homepage and try to do an add to cart when there are no previously added items

### Expected result (*)

After adding to the cart, the product should show in a mini cart

### Actual result (*)

Minicart is empty on the homepage. If we go to other pages the mini cart gets updated

**Comment by Tuvpt** [comment]
Thank you for your interest in our module.
I checked and reproduced your problem but that doesn't happen
https://ttprivatenew.s3.amazonaws.com/pulse/bon9x83-gmail/attachments/16284882/TinyTake17-03-2021-01-47-36.mp4

iIt may be related to the ajax cart module on your site. Please check it again
