### ISSUE TITLE
Multiple Slider on one page not working

### ISSUE THREAD

**Issue by dennismetz** [mageplaza/magento-2-product-slider#91]
### Preconditions (*)
1. Magento Ver.-2.4.3-p1
2. Mageplaza Product Slider 4.0.2

### Steps to reproduce (*)
1. Create CMS Page
2. Include 2 Slider:
2.1 {{widget type="Mageplaza\Productslider\Block\Widget\Slider" title="yyyyyyy" products_count="15" product_type="mostviewed"}}
2.2  {{widget type="Mageplaza\Productslider\Block\Widget\Slider" title="xxxxxxx" products_count="15" product_type="best-seller"}}
3. Go to Shop > Settings/Configuration > MagePlaza Extensions > Productslider > Enable next/prev
4. Click next/prev in frontend 

### Expected result (*)
1. Click next/prev should only work for slider 1 if you click on prev/next on first slider

### Actual result (*)
1. If you click next/prev on first slider the second one is scrolled

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza.
I have checked from my side and our extension still working well: https://www.dropbox.com/s/km36uju9mhi5nv2/github_productslider_91.webm?dl=0

In your case, please submit a ticket to get better support. You can contact us here: https://www.mageplaza.com/contact.html
Thank you!

**Comment by giaphn** [comment]
Closed due to no response in 7 days.
